import type { FastifyPluginAsync } from "fastify";
import { z } from "zod";
import { prisma } from "@wacalls/database";
import { hashPassword, randomToken, sha256 } from "@wacalls/auth";
import { ok, ROLES } from "@wacalls/shared";
import { sendMail } from "../services/mail.js";
import { env } from "../env.js";

export const userRoutes: FastifyPluginAsync = async (app) => {
  app.get("/users", async (req) => {
    const auth = await app.authenticate(req);
    await app.requirePermission("users.view")(req).catch(async () => {
      await app.requirePermission("users.manage")(req);
    });
    const members = await prisma.organizationUser.findMany({
      where: { organizationId: auth.orgId },
      include: { user: { select: { id: true, email: true, name: true, isActive: true } } },
    });
    return ok(members);
  });

  app.post("/users/invite", async (req) => {
    const auth = await app.authenticate(req);
    await app.requirePermission("users.manage")(req);
    const body = z
      .object({
        email: z.string().email(),
        name: z.string(),
        role: z.enum(ROLES),
        password: z.string().min(10).optional(),
      })
      .parse(req.body);
    const password = body.password ?? randomToken(8);
    const user = await prisma.$transaction(async (tx) => {
      const existing = await tx.user.findUnique({ where: { email: body.email.toLowerCase() } });
      const u =
        existing ??
        (await tx.user.create({
          data: {
            email: body.email.toLowerCase(),
            name: body.name,
            passwordHash: await hashPassword(password),
          },
        }));
      await tx.organizationUser.upsert({
        where: { organizationId_userId: { organizationId: auth.orgId, userId: u.id } },
        update: { role: body.role },
        create: { organizationId: auth.orgId, userId: u.id, role: body.role },
      });
      return u;
    });
    if (!body.password) {
      await sendMail(
        body.email,
        "You were invited to WaCalls",
        `Login at ${env.APP_URL}/login\nEmail: ${body.email}\nTemporary password was generated by your admin.`,
      );
    }
    return ok({ id: user.id, email: user.email });
  });

  app.patch("/users/:id/presence", async (req) => {
    const auth = await app.authenticate(req);
    const body = z.object({ presence: z.enum(["READY", "BUSY", "OFFLINE"]) }).parse(req.body);
    await prisma.organizationUser.updateMany({
      where: { organizationId: auth.orgId, userId: auth.sub },
      data: { presence: body.presence },
    });
    return ok({ presence: body.presence });
  });

  app.post("/users/invite-token", async (req) => {
    const auth = await app.authenticate(req);
    await app.requirePermission("users.manage")(req);
    const body = z.object({ email: z.string().email(), role: z.enum(ROLES) }).parse(req.body);
    const token = randomToken();
    await prisma.invitation.create({
      data: {
        organizationId: auth.orgId,
        email: body.email.toLowerCase(),
        role: body.role,
        tokenHash: sha256(token),
        expiresAt: new Date(Date.now() + 7 * 86400_000),
      },
    });
    return ok({ token });
  });
};
