ALTER TABLE "campaigns" ADD COLUMN IF NOT EXISTS "delay_between_calls_sec" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "campaigns" ADD COLUMN IF NOT EXISTS "ring_timeout_sec" INTEGER NOT NULL DEFAULT 60;
ALTER TABLE "campaigns" ADD COLUMN IF NOT EXISTS "batch_size" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "campaigns" ADD COLUMN IF NOT EXISTS "sleep_after_batch_sec" INTEGER NOT NULL DEFAULT 0;
